version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-change-this-secret-key}
      - SNIPPET_USERNAME=${SNIPPET_USERNAME:-admin}
      - SNIPPET_PASSWORD=${SNIPPET_PASSWORD:-changeme}
    volumes:
      - ./data:/app/data
      - ./snippets.db:/app/snippets.db
    restart: unless-stopped
